### ISSUE TITLE
conduit-algorithms-0.0.7.2 build failure with conduit-1.3

### ISSUE THREAD

**Issue by DanBurton** [luispedro/conduit-algorithms#6]
As seen on the Stackage build server:

```
[3 of 5] Compiling Data.Conduit.Algorithms.Async ( Data/Conduit/Algorithms/Async.hs, dist/build/Data/Conduit/Algorithms/Async.o )

Data/Conduit/Algorithms/Async.hs:48:63: error:
    Module
    ‘Control.Monad.Trans.Resource’
    does not export
    ‘MonadBaseControl’
   |
48 | import           Control.Monad.Trans.Resource (MonadResource, MonadBaseControl)
   |                                                               ^^^^^^^^^^^^^^^^
```

Here's how I reproduced the failure locally:

```bash
stack unpack conduit-algorithms-0.0.7.2 && cd conduit-algorithms-0.0.7.2
edit stack.yaml # add the following stack.yaml
stack build
```

```yaml
# stack.yaml
resolver: nightly-2018-03-10
extra-deps:
- conduit-1.3.0
- resourcet-1.2.0
- bzlib-conduit-0.3.0
- cereal-conduit-0.8.0
- conduit-extra-1.3.0
- conduit-combinators-1.3.0
- stm-conduit-4.0.0
```
